
INSERT INTO `centre_vaccination` (`id`, `adress`, `nom`) VALUES
(25, 'Tam Điệp', 'Christen Best'),
(27, 'Chihuahua', 'Amity Beck'),
(28, 'Matiari', 'Ishmael O\'brien'),
(29, 'Forchies-la-Marche', 'Connor Taylor'),
(30, 'Maintal', 'Harper Douglas'),
(31, 'Sandy', 'Martin Robbins'),
(32, 'Querétaro', 'Dorian Franks'),
(33, 'Zirl', 'Lucy Young'),
(34, 'Alexandra', 'Nigel Christian'),
(35, 'Lisieux', 'Ramona Baxter'),
(36, 'Puerto Vallarta', 'Jena Phillips'),
(37, 'Himamaylan', 'Zeph Diaz'),
(38, 'Oberpullendorf', 'Hiram Skinner'),
(39, 'Temuka', 'Aurelia Wong'),
(40, 'Istanbul', 'Ray Pope'),
(41, 'Cork', 'Yetta Brennan'),
(42, 'Villa Cortese', 'Zachery Jimenez'),
(43, 'Gilgit', 'Natalie Luna'),
(44, 'Arbroath', 'Berk Sargent'),
(45, 'Wemmel', 'Hillary Wall'),
(46, 'Villahermosa', 'Hamish Carrillo'),
(47, 'Berlin', 'Abra Howard'),
(48, 'Gävle', 'Alan Morrison'),
(49, 'Sakhalin', 'Oliver Warner'),
(50, 'Cusco', 'Guinevere Giles'),
(51, 'Baguio', 'Frances Lucas'),
(52, 'Mont', 'Vera Maddox'),
(53, 'Nicoya', 'Xyla Reeves'),
(54, 'Zielona Góra', 'Laith Adkins'),
(55, 'Cuttack', 'Oren Welch'),
(56, 'Sneek', 'Lee Moon'),
(57, 'Motueka', 'Hunter Koch'),
(58, 'Zwettl-Niederösterreich', 'Mohammad Gonzales'),
(59, 'Kurram Agency', 'Haviva Garza'),
(60, 'Gijón', 'Cheryl Mcmillan'),
(61, 'Musina', 'Dean Sosa'),
(62, 'Gorontalo', 'Aiko Larson'),
(63, 'Dutse', 'Jasper Kirk'),
(64, 'Finspång', 'Thor Blanchard'),
(65, 'Mianwali', 'Jasper Hewitt'),
(66, 'Ibagué', 'Rafael Hill'),
(67, 'Seoul', 'Judah Pugh'),
(68, 'Salvador', 'Joel Briggs'),
(69, 'Saint-Étienne-du-Rouvray', 'Sarah Skinner'),
(70, 'Huntly', 'Willa Cruz'),
(71, 'Uyo', 'Dillon Odom'),
(72, 'Parndorf', 'Malcolm Bailey'),
(73, 'Maiduguri', 'Kirk Stuart'),
(74, 'Levanger', 'Caesar Orr'),
(75, 'Olinda', 'Rooney Patel'),
(76, 'Divinópolis', 'Kyle Arnold'),
(77, 'Carleton', 'Ronan Mann'),
(78, 'Ipswich', 'Alice Logan'),
(79, 'Kuşadası', 'Damian Dyer'),
(80, 'Yungay', 'Bruno Salinas'),
(81, 'Fort Worth', 'Madaline Diaz'),
(82, 'Mango', 'Priscilla Orr'),
(83, 'North Berwick', 'Ainsley Walter'),
(84, 'Okene', 'Clarke Vaughan'),
(85, 'Freiberg', 'Josephine Sharpe'),
(86, 'Tacurong', 'Fitzgerald Hatfield'),
(87, 'Coevorden', 'Lunea O\'brien'),
(88, 'Konin', 'Cooper Richmond'),
(89, 'Thalassery', 'Hop Ayers'),
(90, 'Eisleben', 'George Clarke'),
(91, 'Götzis', 'Suki Peters'),
(92, 'Monteu Roero', 'Karly Joyce'),
(93, 'Gönen', 'Julian Cummings'),
(94, 'Antakya', 'Eric Brennan'),
(95, 'Pacasmayo', 'Bradley Clemons'),
(96, 'Vetlanda', 'Dillon Meadows'),
(97, 'Belfast', 'Bryar Pearson'),
(98, 'Zamboanga City', 'Rinah Wise'),
(99, 'Baguio', 'Amir Barber'),
(100, 'Oban', 'Rebecca Whitley'),
(101, 'Borlänge', 'Ferris Tanner'),
(102, 'Sale', 'Steel Sweet'),
(103, 'Great Falls', 'Julian Hodge'),
(104, 'Guadalajara', 'Yvonne Rogers'),
(105, 'Pangkalpinang', 'Molly Marsh'),
(106, 'Parañaque', 'Melanie Perez'),
(107, 'Bremen', 'Aidan Bush'),
(108, 'Mandai', 'Alden Hardin'),
(109, 'Whitby', 'Cullen Mercer'),
(110, 'Katihar', 'Urielle Garrison'),
(111, 'Ceyhan', 'Amelia Simpson'),
(112, 'Ilhéus', 'Shaeleigh Anderson'),
(113, 'Åkersberga', 'Damian Reese'),
(114, 'Ilagan', 'Samson Huffman'),
(115, 'Santander', 'Veda Fuentes'),
(116, 'Vienna', 'Barclay Bentley'),
(117, 'Anamur', 'Forrest Fitzgerald'),
(118, 'Wolfurt', 'Cassady Hinton'),
(119, 'Kielce', 'Dorian Beard'),
(120, 'Istmina', 'Jarrod Puckett'),
(121, 'Pskov', 'Quin Knapp'),
(122, 'Waren', 'Wendy Shepherd'),
(123, 'Odendaalsrus', 'Fitzgerald Stein'),
(124, 'settat', 'centre1');

-- --------------------------------------------------------

